# Generated by Django 4.2 on 2025-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_campaign_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='batch_size',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='delay_between_batches',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='campaign',
            name='delay_between_messages',
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_speed',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo'), ('sending', 'Enviando'), ('paused', 'Pausado'), ('completed', 'Completado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
    ]
