# Generated by Django 4.2 on 2025-12-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_campaign_batch_size_campaign_delay_between_batches_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingmessage',
            options={'ordering': ['-created_at', 'line_number']},
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='attachment_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='attachment_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='line_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_messages', to='whatsapp.outgoingmessage'),
        ),
    ]
