# Generated by Django 4.2 on 2025-12-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_alter_outgoingmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('sending', 'sending'), ('sent', 'sent'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
