# Generated by Django 4.2 on 2025-12-03 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp', '0006_alter_outgoingmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Prueba Gratuita (30 días)'), ('active', 'Activa'), ('expired', 'Vencida'), ('suspended', 'Suspendida')], default='trial', max_length=20)),
                ('plan', models.CharField(choices=[('trial', 'Prueba - 30 días gratis'), ('initial', 'Activación Inicial - 3 meses ($45)'), ('monthly', 'Mensual - $15/mes')], default='trial', max_length=20)),
                ('trial_started', models.DateTimeField(auto_now_add=True)),
                ('trial_ends', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('has_paid_initial', models.BooleanField(default=False)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('transfer', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('stripe', 'Tarjeta (Stripe)'), ('cash', 'Efectivo'), ('other', 'Otro')], max_length=20)),
                ('plan_type', models.CharField(choices=[('trial', 'Prueba - 30 días gratis'), ('initial', 'Activación Inicial - 3 meses ($45)'), ('monthly', 'Mensual - $15/mes')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='whatsapp.subscription')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
